# Configuration Makefile fragment

# Build the libxml2 binding?
# yes | no
WITH_LIBXML_BINDING := no

# Build the expat binding?
# yes | no
WITH_EXPAT_BINDING := no

# Build the hubbub binding?
# yes | no
WITH_HUBBUB_BINDING := yes

# ----------------------------------------------------------------------------
# BeOS-specific options
# ----------------------------------------------------------------------------
ifeq ($(BUILD),i586-pc-haiku)
  # temporary
  WITH_LIBXML_BINDING := no
endif

-include Makefile.config.override

